import express from 'express';
import { isAuthenticate } from '../auth/isAuthenticate.js';
import { roleMiddleware } from '../../middleware/roleMiddleware.js';
import { cartController } from './cart.controller.js';
const router=express.Router();
router.post("/",isAuthenticate,cartController.addToCart);
router.get("/",isAuthenticate,roleMiddleware('ADMIN'),cartController.getAllCart);
router.get("/:id",isAuthenticate,roleMiddleware('ADMIN'),cartController.getCartByUserId);
router.get("/product/:id",isAuthenticate,roleMiddleware('ADMIN'),cartController.getCartByProductId);
export default router;